[project]
name = "mvsinfoa"
version = "2.0.0-dev"
type = "application"

[mvs.build.datasets.punch]
suffix = "OBJECT"
dsorg = "PO"
recfm = "FB"
lrecl = 80
blksize = 3120
space = ["TRK", 5, 2, 5]

[mvs.build.datasets.ncalib]
suffix = "NCALIB"
dsorg = "PO"
recfm = "U"
lrecl = 0
blksize = 32760
space = ["TRK", 5, 2, 5]

[mvs.build.datasets.syslmod]
suffix = "LOAD"
dsorg = "PO"
recfm = "U"
lrecl = 0
blksize = 32760
space = ["TRK", 5, 2, 5]

[dependencies]
"mvslovers/crent370" = ">=1.0.0"
"mvslovers/mbt-example-lib" = "=2.0.0-dev"

[link.module]
name = "MVSINFOA"
options = ["LIST", "XREF", "LET"]

[link.module.dep_includes]
"mvslovers/mbt-example-lib" = "*"

[artifacts]
mvs = true
